window.ATELIER_DATA = {
  brand: {
    name: "ATELIER NOIR",
    tagline: { en: "Wear the Silence.", fa: "سکوت را بپوش." },
    currencyRate: 62000,
  },
  products: [
    {
      slug: "noir-silk-blazer",
      gender: "women",
      category: "blazer",
      name: { en: "Noir Silk Blazer", fa: "بلیزر ابریشمی نوآر" },
      price: 620,
      color: "black",
      fabric: "silk",
      size: ["XS", "S", "M", "L"],
      season: "aw26",
      badge: "Editor's Pick",
      sustainability: 92,
      rating: 4.9,
      origin: "Italy",
      fit: "Hourglass sharp",
      image:
        "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-fashion-model-walking-down-a-runway-39875-large.mp4",
      story:
        "A liquid silk tailoring piece cut with midnight discipline and pearl lining.",
      trace: ["Mulberry farm", "Como mill", "Tehran atelier", "Your wardrobe"],
    },
    {
      slug: "champagne-trench",
      gender: "women",
      category: "outerwear",
      name: { en: "Champagne Trench", fa: "ترنچ شامپاینی" },
      price: 740,
      color: "champagne",
      fabric: "cotton",
      size: ["S", "M", "L"],
      season: "ss26",
      badge: "New",
      sustainability: 88,
      rating: 4.8,
      origin: "France",
      fit: "Long column",
      image:
        "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-woman-modeling-on-a-catwalk-39797-large.mp4",
      story: "Architectural weather cloth washed in champagne pigment.",
      trace: ["Organic farm", "Lyon dye house", "Paris atelier", "You"],
    },
    {
      slug: "ivory-pleated-dress",
      gender: "women",
      category: "dress",
      name: { en: "Ivory Pleated Dress", fa: "پیراهن پلیسه عاجی" },
      price: 880,
      color: "ivory",
      fabric: "linen",
      size: ["XS", "S", "M"],
      season: "ss26",
      badge: "Bestseller",
      sustainability: 94,
      rating: 4.9,
      origin: "Portugal",
      fit: "Airy A-line",
      image:
        "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-woman-model-posing-in-a-fashion-shoot-39874-large.mp4",
      story:
        "Sun-bleached linen pleats engineered to move like soft architecture.",
      trace: ["Flax field", "Porto mill", "Lisbon atelier", "You"],
    },
    {
      slug: "blush-satin-slip",
      gender: "women",
      category: "dress",
      name: { en: "Blush Satin Slip", fa: "اسلیپ ساتن صورتی" },
      price: 510,
      color: "blush",
      fabric: "satin",
      size: ["XS", "S", "M", "L"],
      season: "holiday",
      badge: "Noir Night",
      sustainability: 81,
      rating: 4.7,
      origin: "Spain",
      fit: "Bias fluid",
      image:
        "https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-fashion-model-in-a-black-dress-on-a-catwalk-39798-large.mp4",
      story: "Bias satin with a whispering blush finish for after-dark rooms.",
      trace: ["Silk farm", "Valencia finish", "Madrid atelier", "You"],
    },
    {
      slug: "smoke-wool-coat",
      gender: "women",
      category: "coat",
      name: { en: "Smoke Wool Coat", fa: "کت پشمی دودی" },
      price: 1120,
      color: "smoke",
      fabric: "wool",
      size: ["S", "M", "L", "XL"],
      season: "fw26",
      badge: "Limited",
      sustainability: 90,
      rating: 4.9,
      origin: "UK",
      fit: "Oversized cocoon",
      image:
        "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-young-model-posing-in-a-fashion-shoot-39877-large.mp4",
      story: "Double-faced merino, hand-finished seams, no visible compromise.",
      trace: ["Regenerative ranch", "Yorkshire mill", "London atelier", "You"],
    },
    {
      slug: "marble-corset-top",
      gender: "women",
      category: "top",
      name: { en: "Marble Corset Top", fa: "تاپ کرستی مرمری" },
      price: 390,
      color: "ivory",
      fabric: "cotton",
      size: ["XS", "S", "M"],
      season: "ss26",
      badge: "New",
      sustainability: 84,
      rating: 4.6,
      origin: "Italy",
      fit: "Sculpted",
      image:
        "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-models-walking-on-a-catwalk-39873-large.mp4",
      story: "Boned cotton jacquard, inspired by quiet Roman interiors.",
      trace: ["Cotton field", "Prato jacquard", "Milan atelier", "You"],
    },
    {
      slug: "noir-wide-leg-trouser-w",
      gender: "women",
      category: "trouser",
      name: { en: "Noir Wide-Leg Trouser", fa: "شلوار گشاد نوآر" },
      price: 460,
      color: "black",
      fabric: "wool",
      size: ["XS", "S", "M", "L", "XL"],
      season: "core",
      badge: "Core",
      sustainability: 86,
      rating: 4.8,
      origin: "Romania",
      fit: "Relaxed tailored",
      image:
        "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-model-walking-on-the-catwalk-39876-large.mp4",
      story: "A disciplined trouser with a dramatic floor-skimming break.",
      trace: ["Wool ranch", "Biella mill", "Bucharest atelier", "You"],
    },
    {
      slug: "linen-sculpt-shirt-w",
      gender: "women",
      category: "shirt",
      name: { en: "Linen Sculpt Shirt", fa: "شومیز لینن مجسمه‌ای" },
      price: 340,
      color: "ivory",
      fabric: "linen",
      size: ["S", "M", "L"],
      season: "ss26",
      badge: "Bestseller",
      sustainability: 96,
      rating: 4.8,
      origin: "Belgium",
      fit: "Boxy refined",
      image:
        "https://images.unsplash.com/photo-1512316609839-ce289d3eba0a?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-model-in-colorful-clothing-walking-on-a-catwalk-39872-large.mp4",
      story:
        "Crisp linen sculpted with a curved back pleat and mother-of-pearl buttons.",
      trace: ["Flax farm", "Flanders mill", "Antwerp atelier", "You"],
    },
    {
      slug: "champagne-knit-set",
      gender: "women",
      category: "knitwear",
      name: { en: "Champagne Knit Set", fa: "ست بافت شامپاینی" },
      price: 590,
      color: "champagne",
      fabric: "wool",
      size: ["XS", "S", "M", "L"],
      season: "fw26",
      badge: "Editor's Pick",
      sustainability: 91,
      rating: 4.9,
      origin: "Peru",
      fit: "Second-skin rib",
      image:
        "https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-woman-on-a-fashion-runway-39878-large.mp4",
      story: "Baby alpaca rib knit with a muted metallic warmth.",
      trace: ["Alpaca cooperative", "Lima spinner", "Cusco atelier", "You"],
    },
    {
      slug: "smoke-silk-scarf",
      gender: "women",
      category: "accessory",
      name: { en: "Smoke Silk Scarf", fa: "روسری ابریشمی دودی" },
      price: 180,
      color: "smoke",
      fabric: "silk",
      size: ["OS"],
      season: "core",
      badge: "Gift",
      sustainability: 89,
      rating: 4.7,
      origin: "Japan",
      fit: "90cm square",
      image:
        "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-fabric-with-a-soft-motion-4445-large.mp4",
      story: "Hand-rolled edges with tonal ink-wash atelier map print.",
      trace: ["Silk farm", "Kyoto print house", "Tokyo finish", "You"],
    },
    {
      slug: "blush-organza-skirt",
      gender: "women",
      category: "skirt",
      name: { en: "Blush Organza Skirt", fa: "دامن ارگانزای صورتی" },
      price: 530,
      color: "blush",
      fabric: "silk",
      size: ["XS", "S", "M"],
      season: "holiday",
      badge: "Limited",
      sustainability: 82,
      rating: 4.6,
      origin: "Korea",
      fit: "Cloud volume",
      image:
        "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-woman-in-a-couture-fashion-show-39799-large.mp4",
      story:
        "Transparent volume held by hidden horsehair and silk organza layers.",
      trace: ["Silk farm", "Seoul organza mill", "Seoul atelier", "You"],
    },
    {
      slug: "ivory-leather-mule",
      gender: "women",
      category: "shoe",
      name: { en: "Ivory Leather Mule", fa: "کفش چرم عاجی" },
      price: 420,
      color: "ivory",
      fabric: "leather",
      size: ["36", "37", "38", "39", "40"],
      season: "core",
      badge: "AR Ready",
      sustainability: 78,
      rating: 4.5,
      origin: "Italy",
      fit: "70mm heel",
      image:
        "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-close-up-of-a-fashion-shoe-39879-large.mp4",
      story:
        "A clean ivory mule with a sculpted champagne heel and WebXR accessory stub.",
      trace: ["Traceable hide", "Tuscan tannery", "Florence atelier", "You"],
    },

    {
      slug: "noir-double-breasted-coat",
      gender: "men",
      category: "coat",
      name: { en: "Noir Double-Breasted Coat", fa: "پالتوی دو دکمه نوآر" },
      price: 1190,
      color: "black",
      fabric: "wool",
      size: ["S", "M", "L", "XL"],
      season: "fw26",
      badge: "Editor's Pick",
      sustainability: 93,
      rating: 4.9,
      origin: "Italy",
      fit: "Structured column",
      image:
        "https://images.unsplash.com/photo-1507680434567-5739c80be1ac?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-man-modelling-clothes-on-a-runway-39880-large.mp4",
      story:
        "Military-weight wool with hand-padded lapels and hidden horn closures.",
      trace: ["Regenerative ranch", "Biella mill", "Milan atelier", "You"],
    },
    {
      slug: "ivory-grandad-shirt",
      gender: "men",
      category: "shirt",
      name: { en: "Ivory Grandad Shirt", fa: "پیراهن یقه دیپلمات عاجی" },
      price: 310,
      color: "ivory",
      fabric: "linen",
      size: ["S", "M", "L", "XL"],
      season: "ss26",
      badge: "Core",
      sustainability: 95,
      rating: 4.8,
      origin: "Portugal",
      fit: "Relaxed",
      image:
        "https://images.unsplash.com/photo-1506634572416-48cdfe530110?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-fashion-model-walking-on-a-catwalk-39881-large.mp4",
      story:
        "Washed linen with invisible placket discipline and a soft grandad collar.",
      trace: ["Flax field", "Porto mill", "Lisbon atelier", "You"],
    },
    {
      slug: "smoke-tailored-trouser",
      gender: "men",
      category: "trouser",
      name: { en: "Smoke Tailored Trouser", fa: "شلوار رسمی دودی" },
      price: 480,
      color: "smoke",
      fabric: "wool",
      size: ["S", "M", "L", "XL"],
      season: "core",
      badge: "Bestseller",
      sustainability: 87,
      rating: 4.8,
      origin: "Romania",
      fit: "Tapered relaxed",
      image:
        "https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-male-model-on-a-fashion-runway-39882-large.mp4",
      story:
        "A smoke-grey trouser with generous pleats and a cinema-length break.",
      trace: ["Wool ranch", "Transylvania mill", "Bucharest atelier", "You"],
    },
    {
      slug: "champagne-suede-jacket",
      gender: "men",
      category: "jacket",
      name: { en: "Champagne Suede Jacket", fa: "ژاکت جیر شامپاینی" },
      price: 980,
      color: "champagne",
      fabric: "suede",
      size: ["S", "M", "L"],
      season: "fw26",
      badge: "Limited",
      sustainability: 76,
      rating: 4.7,
      origin: "Spain",
      fit: "Cropped box",
      image:
        "https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-man-walking-on-a-fashion-runway-39883-large.mp4",
      story: "Velvety suede with a cropped proportion, lined in tonal satin.",
      trace: ["Traceable hide", "Spanish tannery", "Madrid atelier", "You"],
    },
    {
      slug: "black-silk-evening-shirt",
      gender: "men",
      category: "shirt",
      name: { en: "Black Silk Evening Shirt", fa: "پیراهن شب ابریشمی مشکی" },
      price: 520,
      color: "black",
      fabric: "silk",
      size: ["S", "M", "L", "XL"],
      season: "holiday",
      badge: "Noir Night",
      sustainability: 84,
      rating: 4.9,
      origin: "Japan",
      fit: "Fluid straight",
      image:
        "https://images.unsplash.com/photo-1536766768598-e09213fdcf22?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-elegant-man-walking-on-runway-39884-large.mp4",
      story: "Heavy silk twill shirt for rooms lit by candles and low piano.",
      trace: ["Silk farm", "Kyoto twill", "Tokyo atelier", "You"],
    },
    {
      slug: "linen-resort-blazer",
      gender: "men",
      category: "blazer",
      name: { en: "Linen Resort Blazer", fa: "بلیزر ریزورت لینن" },
      price: 690,
      color: "ivory",
      fabric: "linen",
      size: ["S", "M", "L", "XL"],
      season: "ss26",
      badge: "New",
      sustainability: 94,
      rating: 4.7,
      origin: "Belgium",
      fit: "Unstructured",
      image:
        "https://images.unsplash.com/photo-1492447166138-50c3889fccb1?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-male-model-in-a-runway-show-39885-large.mp4",
      story:
        "Canvas-free linen blazer with a shoulder so soft it behaves like a shirt.",
      trace: ["Flax farm", "Flanders mill", "Antwerp atelier", "You"],
    },
    {
      slug: "noir-knit-polo",
      gender: "men",
      category: "knitwear",
      name: { en: "Noir Knit Polo", fa: "پولوی بافت نوآر" },
      price: 360,
      color: "black",
      fabric: "wool",
      size: ["S", "M", "L", "XL"],
      season: "core",
      badge: "Bestseller",
      sustainability: 91,
      rating: 4.8,
      origin: "Peru",
      fit: "Slim rib",
      image:
        "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-man-in-black-clothes-on-runway-39886-large.mp4",
      story: "Extra-fine merino polo with a near-monastic profile.",
      trace: ["Merino farm", "Lima spinner", "Cusco atelier", "You"],
    },
    {
      slug: "blush-cashmere-sweater",
      gender: "men",
      category: "knitwear",
      name: { en: "Blush Cashmere Sweater", fa: "پلیور کشمیر صورتی" },
      price: 620,
      color: "blush",
      fabric: "cashmere",
      size: ["S", "M", "L"],
      season: "fw26",
      badge: "Editor's Pick",
      sustainability: 88,
      rating: 4.9,
      origin: "Mongolia",
      fit: "Relaxed",
      image:
        "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-man-wearing-a-sweater-on-runway-39887-large.mp4",
      story:
        "A restrained blush cashmere sweater, brushed twice for a quiet halo.",
      trace: ["Cashmere herd", "Ulaanbaatar mill", "Noir atelier", "You"],
    },
    {
      slug: "smoke-leather-derby",
      gender: "men",
      category: "shoe",
      name: { en: "Smoke Leather Derby", fa: "دربی چرمی دودی" },
      price: 560,
      color: "smoke",
      fabric: "leather",
      size: ["40", "41", "42", "43", "44"],
      season: "core",
      badge: "AR Ready",
      sustainability: 79,
      rating: 4.7,
      origin: "Italy",
      fit: "Goodyear welt",
      image:
        "https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-close-up-of-mens-shoes-39888-large.mp4",
      story:
        "Smoke-polished derby, welted for decades and ready for AR room preview.",
      trace: ["Traceable hide", "Tuscan tannery", "Florence atelier", "You"],
    },
    {
      slug: "champagne-silk-tie",
      gender: "men",
      category: "accessory",
      name: { en: "Champagne Silk Tie", fa: "کراوات ابریشمی شامپاینی" },
      price: 160,
      color: "champagne",
      fabric: "silk",
      size: ["OS"],
      season: "holiday",
      badge: "Gift",
      sustainability: 86,
      rating: 4.6,
      origin: "France",
      fit: "7cm blade",
      image:
        "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-fabric-with-golden-light-4446-large.mp4",
      story: "Seven-fold silk with a muted glimmer, never loud.",
      trace: ["Silk farm", "Lyon jacquard", "Paris finish", "You"],
    },
    {
      slug: "ivory-cotton-tank",
      gender: "men",
      category: "top",
      name: { en: "Ivory Cotton Tank", fa: "تاپ پنبه‌ای عاجی" },
      price: 140,
      color: "ivory",
      fabric: "cotton",
      size: ["S", "M", "L", "XL"],
      season: "ss26",
      badge: "Core",
      sustainability: 90,
      rating: 4.5,
      origin: "Turkey",
      fit: "Athletic",
      image:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-man-posing-in-fashion-shoot-39889-large.mp4",
      story: "Dense organic cotton tank, cut to sit clean under tailoring.",
      trace: ["Organic field", "Izmir knit", "Istanbul atelier", "You"],
    },
    {
      slug: "noir-weekend-bag",
      gender: "men",
      category: "accessory",
      name: { en: "Noir Weekend Bag", fa: "ساک آخر هفته نوآر" },
      price: 790,
      color: "black",
      fabric: "leather",
      size: ["OS"],
      season: "core",
      badge: "AR Ready",
      sustainability: 82,
      rating: 4.8,
      origin: "Italy",
      fit: "42L",
      image:
        "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=80",
      video:
        "https://assets.mixkit.co/videos/preview/mixkit-leather-fashion-accessory-39890-large.mp4",
      story:
        "A weekend bag with quiet hardware and a passport-style traceability card.",
      trace: ["Traceable hide", "Tuscan tannery", "Florence atelier", "You"],
    },
  ],
  journal: [
    {
      title: { en: "The Return of Quiet Tailoring", fa: "بازگشت دوخت آرام" },
      image:
        "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=80",
      minutes: 7,
      tag: "Silhouette",
      tall: true,
    },
    {
      title: {
        en: "How Silk Learns the Body",
        fa: "چگونه ابریشم بدن را یاد می‌گیرد",
      },
      image:
        "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=1200&q=80",
      minutes: 5,
      tag: "Fabric",
      tall: false,
    },
    {
      title: {
        en: "Noir Cities: Tehran After Rain",
        fa: "شهرهای نوآر: تهران پس از باران",
      },
      image:
        "https://images.unsplash.com/photo-1536766820879-059fec98ec0a?auto=format&fit=crop&w=1200&q=80",
      minutes: 9,
      tag: "Travel",
      tall: true,
    },
    {
      title: { en: "A Map of Responsible Wool", fa: "نقشه پشم مسئولانه" },
      image:
        "https://images.unsplash.com/photo-1542060748-10c28b62716f?auto=format&fit=crop&w=1200&q=80",
      minutes: 6,
      tag: "Sustainability",
      tall: false,
    },
    {
      title: {
        en: "The Blush That Behaves Like Grey",
        fa: "صورتی‌ای که مانند خاکستری رفتار می‌کند",
      },
      image:
        "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
      minutes: 4,
      tag: "Palette",
      tall: false,
    },
  ],
};
